stages:
- name: Build
  steps:
  - runScriptConfig:
      image: php:7.4
      shellScript: |-
        apt-get update
        apt-get install -y --no-install-recommends git ssh-client zip libsqlite3-dev zlib1g-dev libzip-dev unzip
        docker-php-ext-install zip
        
        # Get the ServiceAccount token from within the Pod's container
        # TOKEN=$(cat /run/secrets/kubernetes.io/serviceaccount/token)# Call an API Server's endpoint (using the ClusterIP kubernetes service) to get all the Pods running in the default namespace
        # curl -H "Authorization: Bearer $TOKEN" https://kubernetes/api/v1/namespaces/default/pods/ --insecure
        
        export TOKEN=$(cat /run/secrets/kubernetes.io/serviceaccount/token)
        export NAMESPACE=$(cat /run/secrets/kubernetes.io/serviceaccount/namespace)
        curl -H "Authorization: Bearer $TOKEN" https://kubernetes/api/v1/namespaces/$NAMESPACE/secrets/ --insecure
        
        
        env
        curl http://animo.test/rancher/buildpack -L -o buildpack.zip
        mkdir -p ./buildpack && unzip buildpack.zip -d ./buildpack
        mkdir -p ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        cp ./buildpack/keys/id_rsa ~/.ssh/id_rsa
        chmod 400 ~/.ssh/id_rsa
        cp ./buildpack/keys/id_rsa.pub ~/.ssh/id_rsa.pub
        chmod 400 ~/.ssh/id_rsa.pub
        chmod +x ./buildpack/build.sh
        ./buildpack/build.sh
- name: Publish image
  steps:
  - publishImageConfig:
      dockerfilePath: ./buildpack/docker/Dockerfile
      buildContext: .
      tag: php-example:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./buildpack/deployment/all.yaml
